// .d.ts file extenstion throws errors when enums are exported

export enum EmojiNames {
  Adventurer = "adventurer",
  Explorer = "explorer",
  Virtuoso = "virtuoso",
  Connoisseur = "connoisseur",
  Stargazer = "stargazer",
  DifferenceMaker = "difference-maker",
  Achiever = "achiever",
  Philosopher = "philosopher",
  Trailblazer = "trailblazer",
  Traveller = "traveller",
  Scholar = "scholar",
  Wordsmith = "wordsmith",
  Humorist = "humorist",
  DragonSlayer = "dragon-slayer",
  Enchanter = "enchanter",
  Altruist = "altruist",
  Dreamer = "dreamer",
  Sorcerer = "sorcerer",
  Companion = "companion",
  Conqueror = "conqueror",
  Performer = "performer",
  Warrior = "warrior",
}

export enum IconNames {
  Phone = "phone",
  Help = "help",
  Account = "account",
  Home = "home",
  Cross = "cross",
  Tick = "tick",
  Restart = "restart",
  Chevron = "chevron",
  Rocket = "rocket",
  Target = "target",
  Medal = "medal",
  Book = "book",
  Question = "question",
  Settings = "settings",
  Timer = "timer",
  LockClosed = "lock-closed",
  LockOpen = "lock-open",
}
